// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgumszitsciqxvvqhfbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndW1zeml0c2NpcXh2dnFoZmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Nzk0NTksImV4cCI6MjA1OTM1NTQ1OX0.gRiNJwsA87y_y-M1JhmDanVWdDp5SwLSCrym7H42MZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);